[Fri, 01 Dec 17 14:44:56 +0800][ERROR] {"file":"C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\LoginRepository.php","line":76,"code":0,"msg":"Cannot resolve attribute 'Name' in the model","trace":"#0 [internal function]: Phalcon\\Mvc\\Model::_invokeFinder('findFirstByName', Array)\n#1 C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\LoginRepository.php(76): Phalcon\\Mvc\\Model::__callStatic('findFirstByName', Array)\n#2 C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\LoginRepository.php(21): App\\Frontend\\Repositories\\LoginRepository->validate(Array)\n#3 C:\\Debug\\www\\phalcon\\app\\frontend\\controllers\\LoginController.php(25): App\\Frontend\\Repositories\\LoginRepository->register(Array)\n#4 [internal function]: App\\Frontend\\Controllers\\LoginController->registerAction()\n#5 [internal function]: Phalcon\\Dispatcher->callActionMethod(Object(App\\Frontend\\Controllers\\LoginController), 'registerAction', Array)\n#6 [internal function]: Phalcon\\Dispatcher->dispatch()\n#7 C:\\Debug\\www\\phalcon\\public\\index.php(130): Phalcon\\Mvc\\Application->handle()\n#8 C:\\Debug\\www\\phalcon\\public\\index.php(140): Application->main()\n#9 {main}"}

[Fri, 01 Dec 17 15:12:09 +0800][ERROR] {"file":"C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\LoginRepository.php","line":39,"code":"23000","msg":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'MwTegnxzMiDE1NjU' for key 'username'","trace":"#0 [internal function]: PDOStatement->execute()\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo->executePrepared(Object(PDOStatement), Array, Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo->execute('INSERT INTO `w_...', Array, Array)\n#3 [internal function]: Phalcon\\Db\\Adapter->insert('w_user', Array, Array, Array)\n#4 [internal function]: Phalcon\\Mvc\\Model->_doLowInsert(Object(Phalcon\\Mvc\\Model\\MetaData\\Memory), Object(Phalcon\\Db\\Adapter\\Pdo\\Mysql), 'w_user', 'id')\n#5 C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\LoginRepository.php(39): Phalcon\\Mvc\\Model->save()\n#6 C:\\Debug\\www\\phalcon\\app\\frontend\\controllers\\LoginController.php(25): App\\Frontend\\Repositories\\LoginRepository->register(Array)\n#7 [internal function]: App\\Frontend\\Controllers\\LoginController->registerAction()\n#8 [internal function]: Phalcon\\Dispatcher->callActionMethod(Object(App\\Frontend\\Controllers\\LoginController), 'registerAction', Array)\n#9 [internal function]: Phalcon\\Dispatcher->dispatch()\n#10 C:\\Debug\\www\\phalcon\\public\\index.php(130): Phalcon\\Mvc\\Application->handle()\n#11 C:\\Debug\\www\\phalcon\\public\\index.php(140): Application->main()\n#12 {main}"}

[Fri, 01 Dec 17 15:12:55 +0800][ERROR] {"file":"C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\LoginRepository.php","line":39,"code":"23000","msg":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'MwTegnxzMiDE1NjU' for key 'username'","trace":"#0 [internal function]: PDOStatement->execute()\n#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo->executePrepared(Object(PDOStatement), Array, Array)\n#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo->execute('INSERT INTO `w_...', Array, Array)\n#3 [internal function]: Phalcon\\Db\\Adapter->insert('w_user', Array, Array, Array)\n#4 [internal function]: Phalcon\\Mvc\\Model->_doLowInsert(Object(Phalcon\\Mvc\\Model\\MetaData\\Memory), Object(Phalcon\\Db\\Adapter\\Pdo\\Mysql), 'w_user', 'id')\n#5 C:\\Debug\\www\\phalcon\\app\\frontend\\repositories\\LoginRepository.php(39): Phalcon\\Mvc\\Model->save()\n#6 C:\\Debug\\www\\phalcon\\app\\frontend\\controllers\\LoginController.php(25): App\\Frontend\\Repositories\\LoginRepository->register(Array)\n#7 [internal function]: App\\Frontend\\Controllers\\LoginController->registerAction()\n#8 [internal function]: Phalcon\\Dispatcher->callActionMethod(Object(App\\Frontend\\Controllers\\LoginController), 'registerAction', Array)\n#9 [internal function]: Phalcon\\Dispatcher->dispatch()\n#10 C:\\Debug\\www\\phalcon\\public\\index.php(130): Phalcon\\Mvc\\Application->handle()\n#11 C:\\Debug\\www\\phalcon\\public\\index.php(140): Application->main()\n#12 {main}"}

[Fri, 01 Dec 17 15:20:54 +0800][ERROR] {"file":"C:\\Debug\\www\\phalcon\\public\\index.php","line":130,"code":2,"msg":"App\\Frontend\\Controllers\\SmsController handler class cannot be loaded","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('App\\\\Frontend\\\\Co...', 2)\n#1 [internal function]: Phalcon\\Dispatcher->dispatch()\n#2 C:\\Debug\\www\\phalcon\\public\\index.php(130): Phalcon\\Mvc\\Application->handle()\n#3 C:\\Debug\\www\\phalcon\\public\\index.php(140): Application->main()\n#4 {main}"}

[Fri, 01 Dec 17 15:58:15 +0800][ERROR] {"file":"C:\\Debug\\www\\phalcon\\public\\index.php","line":130,"code":2,"msg":"App\\Frontend\\Controllers\\SmsController handler class cannot be loaded","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('App\\\\Frontend\\\\Co...', 2)\n#1 [internal function]: Phalcon\\Dispatcher->dispatch()\n#2 C:\\Debug\\www\\phalcon\\public\\index.php(130): Phalcon\\Mvc\\Application->handle()\n#3 C:\\Debug\\www\\phalcon\\public\\index.php(140): Application->main()\n#4 {main}"}

[Fri, 01 Dec 17 15:58:24 +0800][ERROR] {"file":"C:\\Debug\\www\\phalcon\\public\\index.php","line":130,"code":2,"msg":"App\\Frontend\\Controllers\\SmsController handler class cannot be loaded","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('App\\\\Frontend\\\\Co...', 2)\n#1 [internal function]: Phalcon\\Dispatcher->dispatch()\n#2 C:\\Debug\\www\\phalcon\\public\\index.php(130): Phalcon\\Mvc\\Application->handle()\n#3 C:\\Debug\\www\\phalcon\\public\\index.php(140): Application->main()\n#4 {main}"}

