[Fri, 06 Oct 17 15:57:42 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'goods' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'goods' ...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Fri, 06 Oct 17 15:57:45 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'goods' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'goods' ...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

