[Sat, 11 Nov 17 17:34:44 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:39:25 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:40:32 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:40:32 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:41:27 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:41:27 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:42:11 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:42:11 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:42:59 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:43:17 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:43:17 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:43:27 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:43:27 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:43:45 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:43:45 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:43:57 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:43:57 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:44:58 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:44:58 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:45:34 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:45:34 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:46:53 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:46:53 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:47:18 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:47:18 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:48:16 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:48:16 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:48:29 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:48:29 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:48:46 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:48:46 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:49:20 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:49:20 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:49:39 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:49:39 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:50:24 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:50:24 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:50:43 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:50:43 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:50:43 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:53:46 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:55:56 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:56:17 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

[Sat, 11 Nov 17 17:57:42 +0800][ERROR] {"file":"\/home\/wwwroot\/default\/phalcon\/public\/index.php","line":129,"code":5,"msg":"Action 'getdate' was not found on handler 'index'","trace":"#0 [internal function]: Phalcon\\Mvc\\Dispatcher->_throwDispatchException('Action 'getdate...', 5)\n#1 [internal function]: Phalcon\\Dispatcher->_dispatch()\n#2 [internal function]: Phalcon\\Dispatcher->dispatch()\n#3 \/home\/wwwroot\/default\/phalcon\/public\/index.php(129): Phalcon\\Mvc\\Application->handle()\n#4 \/home\/wwwroot\/default\/phalcon\/public\/index.php(139): Application->main()\n#5 {main}"}

